// Copyright 2026 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

import Foundation
import GRDB
import LibSignalClient
import SignalCore
import SignalStorage
import SwiftProtobuf

/// Counts acks (thread-safe; acks arrive from the receiver's actor).
final class AckCounter: @unchecked Sendable {
    private let lock = NSLock()
    private var counts = [Int]()

    /// An `IncomingEnvelope` whose ack increments this counter's slot.
    func envelope(_ bytes: Data) -> IncomingEnvelope {
        let slot: Int = lock.withLock {
            counts.append(0)
            return counts.count - 1
        }
        return IncomingEnvelope(bytes: bytes, ack: { [self] in
            lock.withLock { counts[slot] += 1 }
        })
    }

    /// Total acks across all envelopes.
    var total: Int {
        lock.withLock { counts.reduce(0, +) }
    }

    /// True when every envelope handed out was acked exactly once.
    var allExactlyOnce: Bool {
        lock.withLock { !counts.isEmpty && counts.allSatisfy { $0 == 1 } }
    }
}

/// A recipient device over an in-memory GRDB database: the real stores the
/// receiver runs against.
final class ReceiverRig: @unchecked Sendable {
    let db: SignalDatabase
    let identity: GRDBIdentityStore
    let session: GRDBSessionStore
    let store: GRDBProtocolStore
    let messages: MessageStore
    let unprocessed: UnprocessedStore
    let conversations: ConversationStore
    let ourAci: String
    let ourDevice: UInt32
    let address: ProtocolAddress
    private var nextOneTimeId: UInt32 = 1000

    init(ourAci: String, ourDevice: UInt32) throws {
        self.ourAci = ourAci.lowercased()
        self.ourDevice = ourDevice
        db = try SignalDatabase.open(path: nil, key: "k")
        identity = GRDBIdentityStore(queue: db.queue)
        session = GRDBSessionStore(queue: db.queue)
        store = GRDBProtocolStore(
            identity: identity,
            session: session,
            senderKeys: GRDBSenderKeyStore(queue: db.queue)
        )
        messages = MessageStore(queue: db.queue)
        unprocessed = UnprocessedStore(queue: db.queue)
        conversations = ConversationStore(queue: db.queue)
        address = try ProtocolAddress(name: self.ourAci, deviceId: ourDevice)
    }

    func receiver(
        trustRoots: [PublicKey],
        writer: (any MessageWriting)? = nil,
        unprocessed override: UnprocessedStore? = nil
    ) throws -> EnvelopeReceiver {
        try EnvelopeReceiver(
            store: store,
            unprocessed: override ?? unprocessed,
            messages: writer ?? messages,
            ourAci: ourAci,
            ourDeviceId: ourDevice,
            trustRoots: trustRoots
        )
    }

    /// Provisions a fresh identity plus signed and Kyber prekeys, the way
    /// linking would (identity from "provisioning", never generated by the
    /// store itself).
    func provisionOwnKeys() throws {
        let context = NullContext()
        try identity.storeAccountIdentity(
            aci: IdentityKeyPair.generate(),
            pni: IdentityKeyPair.generate(),
            registrationId: generateRegistrationId()
        )
        let ownIdentity = try identity.identityKeyPair(context: context)
        let signed = PrivateKey.generate()
        let signedSig = ownIdentity.privateKey.generateSignature(message: signed.publicKey.serialize())
        let kyber = KEMKeyPair.generate()
        let kyberSig = ownIdentity.privateKey.generateSignature(message: kyber.publicKey.serialize())
        try session.storeSignedPreKey(
            SignedPreKeyRecord(id: 3006, timestamp: 42000, privateKey: signed, signature: signedSig),
            id: 3006,
            context: context
        )
        try session.storeKyberPreKey(
            KyberPreKeyRecord(id: 8888, timestamp: 42000, keyPair: kyber, signature: kyberSig),
            id: 8888,
            context: context
        )
        signedPublic = signed.publicKey
        signedSignature = signedSig
        kyberPublic = kyber.publicKey
        kyberSignature = kyberSig
    }

    private var signedPublic: PublicKey?
    private var signedSignature: Data?
    private var kyberPublic: KEMPublicKey?
    private var kyberSignature: Data?

    /// A new prekey bundle for this device, minting (and storing) a fresh
    /// one-time prekey so each sender consumes its own.
    func makeBundle() throws -> PreKeyBundle {
        let context = NullContext()
        nextOneTimeId += 1
        let id = nextOneTimeId
        let oneTime = PrivateKey.generate()
        try session.storePreKey(PreKeyRecord(id: id, privateKey: oneTime), id: id, context: context)
        return try PreKeyBundle(
            registrationId: identity.localRegistrationId(context: context),
            deviceId: ourDevice,
            prekeyId: id,
            prekey: oneTime.publicKey,
            signedPrekeyId: 3006,
            signedPrekey: signedPublic!,
            signedPrekeySignature: signedSignature!,
            identity: identity.identityKeyPair(context: context).identityKey,
            kyberPrekeyId: 8888,
            kyberPrekey: kyberPublic!,
            kyberPrekeySignature: kyberSignature!
        )
    }

    func rowCount(_ table: String) throws -> Int {
        try db.queue.read { db in
            try Int.fetchOne(db, sql: "SELECT COUNT(*) FROM \(table)") ?? 0
        }
    }
}

/// A remote sender with its own in-memory libsignal store.
final class TestPeer {
    let store = InMemorySignalProtocolStore()
    let aci: String
    let deviceId: UInt32
    let address: ProtocolAddress

    init(aci: String, deviceId: UInt32) throws {
        self.aci = aci.lowercased()
        self.deviceId = deviceId
        address = try ProtocolAddress(name: self.aci, deviceId: deviceId)
    }

    func establish(with bundle: PreKeyBundle, recipient: ProtocolAddress) throws {
        try processPreKeyBundle(
            bundle,
            for: recipient,
            ourAddress: address,
            sessionStore: store,
            identityStore: store,
            context: NullContext()
        )
    }

    /// Pads `content` like Desktop does, then encrypts it for `recipient`.
    func encrypt(content: Data, to recipient: ProtocolAddress) throws -> CiphertextMessage {
        try encryptRaw(padded: Padding.pad(content), to: recipient)
    }

    /// Encrypts bytes exactly as given (to produce bad padding).
    func encryptRaw(padded: Data, to recipient: ProtocolAddress) throws -> CiphertextMessage {
        try signalEncrypt(
            message: padded,
            for: recipient,
            localAddress: address,
            sessionStore: store,
            identityStore: store,
            context: NullContext()
        )
    }

    func senderCertificate(root: IdentityKeyPair, server: IdentityKeyPair) throws -> SenderCertificate {
        try SenderCertificate(
            sender: SealedSenderAddress(e164: nil, uuidString: aci, deviceId: deviceId),
            publicKey: store.identityKeyPair(context: NullContext()).publicKey,
            expiration: UInt64(Date().timeIntervalSince1970 * 1000) + 86_400_000,
            signerCertificate: ServerCertificate(
                keyId: 1,
                publicKey: server.publicKey,
                trustRoot: root.privateKey
            ),
            signerKey: server.privateKey
        )
    }
}

/// Test-only: wraps libsignal-produced ciphertext in a real `Envelope`
/// protobuf (the server's job in production). Invents no wire format.
func wrapInEnvelope(
    type: SignalServiceProtos_Envelope.TypeEnum,
    content: Data?,
    source: (aci: String, device: UInt32)? = nil,
    destination: String,
    clientTimestamp: UInt64,
    guid: String = UUID().uuidString.lowercased()
) throws -> Data {
    var envelope = SignalServiceProtos_Envelope()
    envelope.type = type
    if let source {
        envelope.sourceServiceID = source.aci
        envelope.sourceDeviceID = source.device
    }
    envelope.destinationServiceID = destination
    envelope.clientTimestamp = clientTimestamp
    if let content {
        envelope.content = content
    }
    envelope.serverGuid = guid
    envelope.serverTimestamp = clientTimestamp + 5
    return try envelope.serializedData()
}

func dataContent(body: String?, timestamp: UInt64) throws -> Data {
    var dataMessage = SignalServiceProtos_DataMessage()
    if let body {
        dataMessage.body = body
    }
    dataMessage.timestamp = timestamp
    var content = SignalServiceProtos_Content()
    content.dataMessage = dataMessage
    return try content.serializedData()
}

/// Loads the golden-vector recipient (envelopes.json) into a fresh rig:
/// identity, registration id and every prekey record, exactly as recorded.
func makeVectorRig() throws -> (rig: ReceiverRig, trustRoot: PublicKey, vectors: [String: Any]) {
    let vectors = try Vectors.load("envelopes")
    let recipient = vectors["recipient"] as! [String: Any]
    let hex = { (key: String) in Vectors.data(hex: recipient[key] as! String)! }
    let rig = try ReceiverRig(
        ourAci: recipient["aci"] as! String,
        ourDevice: (recipient["deviceId"] as! NSNumber).uint32Value
    )
    let context = NullContext()
    try rig.identity.storeAccountIdentity(
        aci: IdentityKeyPair(
            publicKey: PublicKey(hex("identityPublic")),
            privateKey: PrivateKey(hex("identityPrivate"))
        ),
        pni: IdentityKeyPair.generate(),
        registrationId: (recipient["registrationId"] as! NSNumber).uint32Value
    )
    let signed = try SignedPreKeyRecord(bytes: hex("signedPreKeyRecord"))
    try rig.session.storeSignedPreKey(signed, id: signed.id, context: context)
    let kyber = try KyberPreKeyRecord(bytes: hex("kyberPreKeyRecord"))
    try rig.session.storeKyberPreKey(kyber, id: kyber.id, context: context)
    for entry in recipient["oneTimePreKeyRecords"] as! [[String: Any]] {
        let record = try PreKeyRecord(bytes: Vectors.data(hex: entry["record"] as! String)!)
        try rig.session.storePreKey(record, id: record.id, context: context)
    }
    let trustRoot = try PublicKey(Vectors.data(hex: vectors["trustRootPublic"] as! String)!)
    return (rig, trustRoot, vectors)
}

/// Collects a receiver's committed messages in the background.
final class ReceivedCollector: @unchecked Sendable {
    private let lock = NSLock()
    private var messages = [ReceivedMessage]()
    private var task: Task<Void, Never>?

    init(_ receiver: EnvelopeReceiver) {
        let stream = receiver.received
        task = Task { [self] in
            for await message in stream {
                lock.withLock { messages.append(message) }
            }
        }
    }

    var all: [ReceivedMessage] {
        lock.withLock { messages }
    }

    func stop(_ receiver: EnvelopeReceiver) async {
        await receiver.finish()
        await task?.value
    }
}

/// A sealed-sender (UNIDENTIFIED_SENDER) envelope from `peer` to `rig`,
/// wrapped in a real Envelope.
func sealedEnvelope(
    from peer: TestPeer,
    to rig: ReceiverRig,
    content: Data,
    clientTimestamp: UInt64,
    root: IdentityKeyPair,
    server: IdentityKeyPair
) throws -> Data {
    let sealed = try sealedSenderEncrypt(
        Padding.pad(content),
        from: peer.senderCertificate(root: root, server: server),
        to: rig.address,
        senderStore: peer.store,
        context: NullContext()
    )
    return try wrapInEnvelope(
        type: .unidentifiedSender,
        content: sealed,
        destination: rig.ourAci,
        clientTimestamp: clientTimestamp
    )
}
